### PR TITLE
perf: use bc-string 

### PR DESCRIPTION
**Pull request by aminya**

### CODE REVIEW

**Comment by burner** [comment]
Sorry for being blunt, but there is no need for this change.

**Comment by burner** [comment]
appender is fast enough

**Comment by aminya** [comment]
I can't think of any downsides to the improvements.
- nogcFormat does formatting at compile time in contrast to parsing the strings during runtime. 
- String is a single owner string that is freed without GC in contrast to GC collected Appender/formattedWrite.

Do you have any benchmarks that prove that? I am interested to know.

**Comment by burner** [comment]
The downside is that it adds another dependency for no real benefit. This code path is not performance critical at all, in a lib that is not performance critical.

> Do you have any benchmarks that prove that?
I don't, if anything, this PR should have a benchmark showing the benefits.

**Comment by aminya** [comment]
For the record, my profiling shows that [my master branch](https://github.com/aminya/argsd/tree/master) is ~3 times faster in a real-world CLI app. For short-living CLI apps, the time spent parsing the arguments can be high.

0.8.1.aminya.1:
image

0.8.1:
image

std.getOpt:

image

**Comment by burner** [comment]
What is the program doing other than parsing args?

IMO this is not worth pulling in the new dependency.
Sorry to be the buzzkill

**Pull request closed without merging**
